### ISSUE TITLE
Allow creating containers using PATCH

### ISSUE THREAD

**Issue by NoelDeMartin** [nodeSolidServer/node-solid-server#1703] opened 2022-09-10 07:05 UTC
Up until recently, I had been using `POST` requests to create new containers in my apps and it was working as expected. This sufficed so far because I was hard-coding the path of containers into my apps, and they were always root-level containers. But for a new app I'm working on I let users decide the path of the new container, and this creates a new situation where intermediate containers may not exist.

In order to solve this, I looked at the [Solid spec](https://solidproject.org/TR/protocol#writing-resources) and saw this:

> Servers MUST create intermediate containers and include corresponding containment triples in container representations derived from the URI path component of PUT and PATCH requests.

So I refactored my code to use `PATCH` instead. But I found out that it does not work as expected with NSS. Here's the result I've been getting:

```sh
curl 'https://localhost:8443/kitchen/cookbook/' \
	-X PATCH \
	-H 'content-type: application/sparql-update' \
	-H 'link: <http://www.w3.org/ns/ldp#BasicContainer>; rel="type"' \
	-H 'if-none-match: *' \
	-H 'authorization: DPoP ...' \
	-H 'dpop: ...' \
	--data-raw 'INSERT DATA { <> <http://www.w3.org/2000/01/rdf-schema#label> "Cookbook" . }'
```

**Response:** Index file needs to have text/html as content type

**Comment by bourgeoa** [comment] 2022-09-10 08:37
> Servers MUST NOT allow HTTP PUT or PATCH on a container to update its containment triples; if the server receives such a request, it MUST respond with a 409 status code. [Source]

I think you are wrong. The above means that you cannot directly create a Container Resource with PUT and PATCH, but must create intermediate containers if you are creating a Document Resource

**Comment by NoelDeMartin** [comment] 2022-09-10 19:04
Thanks @bourgeoa!

Turns out I was using an old version of NSS locally and I didn't realize :sweat_smile:, sorry about that. I tried using `PUT` and it works as expected, so I think that's what I'll do in my apps.

> I don't understand your use of slug

I was using that header to create containers using `POST`, but you're right that it's not necessary using `PUT`.

> PATCH should only work on Document Resource

Where is that specified? Reading [the current spec](https://solidproject.org/TR/protocol#writing-resources) I didn't find anything about it.

This is not a problem for my app anymore, because `PUT` seems to work for my use-case. But given that this is potentially a conflict with the spec I think I should leave this issue open. If you can clarify where that part is documented, I'll close the issue (or feel free to close it yourself :D).

**Comment by bourgeoa** [comment] 2022-09-10 19:25
PATCH can only use N3 patch for the time being

**Comment by NoelDeMartin** [comment] 2022-09-11 07:54
@bourgeoa Just to clarify though, is that a limitation of node-solid-server or is that part of the Solid Protocol?

**Comment by bourgeoa** [comment] 2022-09-11 08:46
I understand that PATCH in Solid his limited to RDF documents. It can create a new document Resource if not exist and all intermediate container Resources. As such it cannot create a Container only. Container representation is not directly writable.
The specification only consider N3 PATCH.

@csarven is this correct.

**Comment by csarven** [comment] 2022-09-12 15:32
This issue is a duplicate of https://github.com/nodeSolidServer/node-solid-server/issues/1465 with the main difference being the HTTP method. Servers are expected to support PATCH to create resources (including containers and non-containers). See also https://solidproject.org/ED/protocol#server-put-patch-uri-assignment

**Comment by zg009** [comment] 2024-04-04 05:26
@csarven The link to the #server-put-patch-uri-assignment is broken. Is there another place to find that link, or has it been removed from the spec?

**Comment by bourgeoa** [comment] 2024-04-04 06:22
Should be closed.

**Comment by csarven** [comment] 2024-04-04 09:32
The requirement https://solidproject.org/ED/protocol#server-put-patch-uri-assignment is dropped. See the ED changelog ( https://solidproject.org/ED/protocol#changelog ).

---

```turtle
@prefix spec: <http://www.w3.org/ns/spec#> .
@prefix ed: <https://solidproject.org/ED/protocol#> .

ed:changelog
  spec:change ed:a91960b6-0543-4acc-8153-689c435c7659 .

ed:afd2402a-3174-4f27-af9d-f80461538e95
  a spec:Change ;
  spec:changeClass spec:ChangeClass2 ;
  spec:changeSubject ed:server-put-patch-uri-assignment ;
  spec:statement "Remove the requirement for implicit and inherited URI assignment after HTTP PUT, PATCH requests that is already defined in referenced specifications."@en .

```

**Closed** 2024-04-06 17:26 UTC
Labels: enhancement
